name: Deploy to Autoscaling Group

on:
  workflow_dispatch:

jobs:
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build and package application
        run: |
          # Your build commands here
          npm install
          # Package your application into a ZIP file
          zip -r app.zip ./*

      - name: Package application
        id: test-id
        run: |
          timestamp=$(date '+%Y-%m-%d_%H-%M-%S')
          artifact_key=my-artifact-$timestamp.zip
          aws s3 cp app.zip s3://${{ secrets.BUCKET_NAME }}/$artifact_key
          echo "artifact_key=$artifact_key" >> "$GITHUB_ENV"

      - name: Create deployment
        run: |
          aws deploy create-deployment \
            --application-name ${{ secrets.APPLICATION_NAME }} \
            --deployment-group-name ${{ secrets.DEPLOYMENT_GROUP_NAME }} \
            --s3-location bucket=${{ secrets.BUCKET_NAME }},key=$artifact_key,bundleType=zip