name: Deploy to Autoscaling Group

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Update Auto Scaling group and terminate previous instances
        run: |
          aws autoscaling update-auto-scaling-group --auto-scaling-group-name auto-scaling-reinel \
              --launch-configuration-name mock-project-template \
              --desired-capacity 0

          # Wait for old instances to terminate
          sleep 300

          aws autoscaling update-auto-scaling-group --auto-scaling-group-name auto-scaling-reinel \
              --launch-configuration-name mock-project-template \
              --desired-capacity 3